### ISSUE TITLE
test_copyto fails in debug mode

### ISSUE THREAD

**Issue by kamilritz** [PX4/Matrix#106]
If you force the build type to be of type `Debug`, and run the tests with `make check`, I got the `test_copyto` to fail.

**Comment by jkflying** [comment]
Can't reproduce from a clean pull on Ubuntu 18.04. test_copyto works as part of the test suite, and also manually in valgrind, both in Debug builds and RelWithDebInfo (edited in the CMakeCache.txt)

@kamilritz do you remember more details of what was failing here? Will re-open if there's an issue I can reproduce.

**Comment by kamilritz** [comment]
Could be that I solved this at some point.
