### ISSUE TITLE
Dcm Type Error

### ISSUE THREAD

**Issue by gnos2010** [PX4/Matrix#135]
If the data type is not float, line 533 of the file Quaternion.hpp will appear a compile error.
If Change  ‘return Quaternion(Dcmf(dcm));’ to ‘return Quaternion(Dcm<Type>(dcm));’
It can adapt to more data types.

**Comment by kamilritz** [comment]
@gnos2010 Thanks for raising this.

**Comment by gnos2010** [comment]
I have been using this Matrix library to do some research work for some weeks. In order to improve the accuracy of numerical calculation, I use double precision floating-point data type. Thank you for your work.

**Comment by gnos2010** [comment]
I sometimes use this Matrix library to do some research work, it is very convenient. TThank you for your work.
