### ISSUE TITLE
Assigning values out of bounds doesn't throw error

### ISSUE THREAD

**Issue by cschindlbeck** [PX4/Matrix#151]
This is possible:
```
matrix::Matrix<double,3,3> testmat;
testmat.setZero();
testmat(2,6) = 2;
```
Shouldn't there be some checking?

**Comment by jgoppert** [comment]
There is an assertion. If you compile with CMAKE_BUILD_TYPE=Debug it will check it for you. Assertions are removed for release builds.

**Comment by cschindlbeck** [comment]
Ok, thanks
