### ISSUE TITLE
Implementation of quaternion derivative

### ISSUE THREAD

**Issue by mkschreder** [PX4/Matrix#27]
Can somebody explain the reason behind the implementation of the derivative function here: https://github.com/PX4/Matrix/blob/master/matrix/Quaternion.hpp#L238-L253

Why does it have to be implemented that way, as opposed to just: 
matrix::Quaternion<float> w(0, _w(0), _w(1), _w(2));
matrix::Quaternion<float> dq = (0.5f * q * w);

(The above code is "textbook" example but it gives wrong results (seems like it results in angles being applied in the wrong order..). Yet it is what I was able to find in the literature so far so I want to know why it does not work).

**Comment by jgoppert** [comment]
When q0 is the scalar of the quaternion, the correct equation is dq = 0.5 * w * q, see (https://arxiv.org/pdf/0811.2889.pdf)

I just switched to this formula on master and added more unit tests. The existing formula was equivalent so no functional change.
