### ISSUE TITLE
Need to be 100% clear about what quaternion convention is used

### ISSUE THREAD

**Issue by mkschreder** [PX4/Matrix#28]
There are many different combinations of quaternion conventions. All have their own peculiarities. Hamilton, STS, JPL, etc. to name a few. We need to be 100% clear about what version of operations is used. 

With this said, hamilton multiplication formula would look like this: 

        r(0) = p(0) * q(0) - p(1) * q(1) - p(2) * q(2) - p(3) * q(3); 
        r(1) = p(0) * q(1) + p(1) * q(0) + p(2) * q(3) - p(3) * q(2); 
        r(2) = p(0) * q(2) - p(1) * q(3) + p(2) * q(0) + p(3) * q(1); 
        r(3) = p(0) * q(3) + p(1) * q(2) - p(2) * q(1) + p(3) * q(0);

Your formula looked like this: 
        r(0) = p(0) * q(0) - p(1) * q(1) - p(2) * q(2) - p(3) * q(3);
        r(1) = p(0) * q(1) + p(1) * q(0) - p(2) * q(3) + p(3) * q(2);
        r(2) = p(0) * q(2) + p(1) * q(3) + p(2) * q(0) - p(3) * q(1);
        r(3) = p(0) * q(3) - p(1) * q(2) + p(2) * q(1) + p(3) * q(0);
        
I'm looking into whether this confusion was causing issues for me. It definitely caused me to mix wrong formulas together. If we agree to use hamilton then following rules would apply: 
- component order: wxyz
- algebra ij = k
- handedness: right
- right to left product means local to global transformation
- default operation: vglobal = q * q(0, vlocal) * q.inversed()

This is important because if someone starts using JPL for example and mix the two in the same code, things will get really really weird in very nontrivial ways.

**Comment by mkschreder** [comment]
Also, you state that your vector multiplication formula is q.inversed() * q(0, v) * q. The glm library convention uses the opposite I believe, because rotating v(1, 0, 0) by quaternion q(cos(rads(90/2)), 0, sin(rads(90/2)), 0) results in r(0, 0, -1). Which was my assumption, but instead I was getting r(0, 0, 1).

**Comment by mkschreder** [comment]
Can we make assumption that rotations are always applied right to left? 

ie. q2 * q1 * v means apply q1 to v first, then apply q2 rotation. 

This would clear things up and be more consistent with how it is done in other places.

**Comment by tumbili** [comment]
@mkschreder 

> v_rotated = q^(-1) * [0;v] * q

The description for the rotation formula seems to be wrong. As you stated above this actually applies a transformation rather than a rotation.

**Comment by jgoppert** [comment]
I switched to Hamilton quaternion def here: https://github.com/PX4/Matrix/commit/19554c4470cd6322ffd18cb20a96485940f226b6 

The unit tests all pass  with previous and current definition, so no significant change, but I agree it is better to follow the common convention. I'm not sure which reference I pulled that from orginaly.

@mkschreder Please post a new issue if you find anything else, thanks for going through the details.

**Comment by mkschreder** [comment]
Roman, vector part of the resulting quaternion from that transformation is
the rotated vector v.

**Comment by mkschreder** [comment]
It is clockwise, as that seems to be the convention when using hamilton
notation (as opposed to positive angle representing counterclockwise
rotation).

**Comment by mkschreder** [comment]
Thanks for fixing this.
