### ISSUE TITLE
coverity low priority defects

### ISSUE THREAD

**Issue by dagar** [PX4/Matrix#36]
Here's a list of matrix defects from Coverity scanning PX4 Firmware. It would be nice to either fix these trivial issues, or tell the scanner to ignore them (if appropriate).

https://scan.coverity.com/projects/px4-firmware/view_defects

![screenshot from 2017-01-04 12-27-10](https://cloud.githubusercontent.com/assets/84712/21652077/30b360d2-d279-11e6-84ad-c09e7015e091.png)

**Comment by jgoppert** [comment]
I had a look at them all. I think we can safely ignore. The are warning about dead code etc. for special template cases where the size is <1, 1> etc.

**Comment by dagar** [comment]
Thanks for looking.
