### ISSUE TITLE
Fix Unit test properly

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Matrix#9]
I changed the hard-coded cast to float to a cast to the type, which now explodes in the unit test:
https://travis-ci.org/PX4/Matrix#L139

However, if I don't do this (and it looks right) it explodes in the PX4 unit test. I think we need to fix it for good here without hard-forcing a specific type in a templated function.

**Comment by LorenzMeier** [comment]
```
/home/travis/build/PX4/Matrix/matrix/helper_functions.hpp: In function ‘Type matrix::wrap_pi(Type) [with Type = double]’:
/home/travis/build/PX4/Matrix/test/helper.cpp:11:5:   instantiated from here
/home/travis/build/PX4/Matrix/matrix/helper_functions.hpp:13:5: error: conversion to ‘float’ from ‘double’ may alter its value [-Werror=conversion]
```

**Comment by LorenzMeier** [comment]
I fixed it for now on master using an ifdef.

**Comment by jgoppert** [comment]
I believe this is resolved now.
